### ISSUE TITLE
Add Hawtio to Platform Manifest

### ISSUE THREAD

**Issue by davgordo** [contract-first-idp/platform-components#14]
Add Hawtio to platform manifest

**Comment by davgordo** [comment]
@smongiar should we deploy a platform-wide centralized instance as well? or will we have one Hawtio instance for every namespace?

**Comment by smongiar** [comment]
Since there would not be a single workspace per user, I don't know about the consequences of multiple users working on the UI. 
When I tested Fuse Console, a few years ago, both cluster and namespaced modes were supported. We could leave it like this, and if experience suggests a different installation mode, we can change it.

Or alternatively, we can talk about it in detail, when I return from vacation :)
